### ISSUE TITLE
UTF-8 Property files.

### ISSUE THREAD

**Issue by HenryMiller** [BrianGarland/RPG-Properties#1]
Hi Brian,
I'm giving a try to your RPG-Properties program.
It works fine except when the IFS file has CCSDI(1208).
In that case the following line returns *NULL 
 // Open the IFS .properties file              
 FileHandle = fOpen(PropertyFile:Mode);  
Best regards,
Giovanni

**Comment by BrianGarland** [comment]
Thank you for finding this issue.  I was able to reproduce it on my system and make a fix.   Please download the latest and give it a try.

**Comment by HenryMiller** [comment]
It works! Sorry for late reply.
